# Generated by Django 3.2.14 on 2022-12-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0003_booksbyotherfathers_sermonsbyotherfthers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SermonsByOtherFthers',
            new_name='SermonsByOtherFathers',
        ),
    ]
