# Generated by Django 3.2.14 on 2022-12-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0004_rename_sermonsbyotherfthers_sermonsbyotherfathers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Litergie',
        ),
    ]
