# Generated by Django 3.2.14 on 2022-12-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0005_delete_litergie'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksbyotherfathers',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermonsbyotherfathers',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
