# Generated by Django 4.1.7 on 2023-04-06 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0006_auto_20221219_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksByOtherFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('book', models.FileField(upload_to='books', verbose_name='book')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('external_link', models.URLField(blank=True, verbose_name='external_link')),
            ],
            options={
                'verbose_name': 'Book by another father',
                'verbose_name_plural': 'Books by other fathers',
            },
        ),
        migrations.CreateModel(
            name='ChosenSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Chosen sermon',
                'verbose_name_plural': 'Chosen sermons',
            },
        ),
        migrations.CreateModel(
            name='SermonsByOtherFather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='author')),
                ('audio', models.FileField(blank=True, upload_to='audio', verbose_name='sermon audio')),
                ('video', models.FileField(blank=True, upload_to='video', verbose_name='video')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('external_link', models.URLField(blank=True, verbose_name='external_link')),
            ],
            options={
                'verbose_name': 'Sermons by other father',
                'verbose_name_plural': 'Sermons by other fathers',
            },
        ),
        migrations.RemoveField(
            model_name='sermonsbyotherfathers',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'Book Category', 'verbose_name_plural': 'Book Categories'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AlterModelOptions(
            name='sermoncategory',
            options={'verbose_name': 'Sermon Category', 'verbose_name_plural': 'Sermon Categories'},
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(default='True', upload_to='books', verbose_name='book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.bookcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='book_category_name'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(blank=True, default='', upload_to='audio', verbose_name='sermon audio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermoncategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='video', verbose_name='video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sermoncategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='sermon_category_name'),
        ),
        migrations.DeleteModel(
            name='BooksByOtherFathers',
        ),
        migrations.DeleteModel(
            name='SermonsByOtherFathers',
        ),
        migrations.AddField(
            model_name='sermonsbyotherfather',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermoncategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='chosensermon',
            name='sermon_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermon', verbose_name='sermon_name'),
        ),
        migrations.AddField(
            model_name='booksbyotherfather',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.bookcategory', verbose_name='category'),
        ),
    ]
