# Generated by Django 4.1.7 on 2023-04-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0007_booksbyotherfather_chosensermon_sermonsbyotherfather_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chosensermon',
            options={'verbose_name': 'Chosen Sermon', 'verbose_name_plural': 'Chosen Sermons'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books', verbose_name='book instance'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.bookcategory', verbose_name='book category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='book title'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='book category name'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='book',
            field=models.FileField(upload_to='books', verbose_name='book instance'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.bookcategory', verbose_name='book category'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='title',
            field=models.CharField(max_length=200, verbose_name='book title'),
        ),
        migrations.AlterField(
            model_name='chosensermon',
            name='sermon_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermon', verbose_name='sermon name'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermoncategory', verbose_name='sermon category'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(max_length=200, verbose_name='sermon title'),
        ),
        migrations.AlterField(
            model_name='sermoncategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='sermon category name'),
        ),
        migrations.AlterField(
            model_name='sermonsbyotherfather',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherpakhomius.sermoncategory', verbose_name='sermon category'),
        ),
        migrations.AlterField(
            model_name='sermonsbyotherfather',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='external link'),
        ),
        migrations.AlterField(
            model_name='sermonsbyotherfather',
            name='title',
            field=models.CharField(max_length=200, verbose_name='sermon title'),
        ),
    ]
