# Generated by Django 4.1.7 on 2023-04-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0008_alter_chosensermon_options_alter_book_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('email_address', models.EmailField(max_length=80, verbose_name='email_address')),
                ('message', models.CharField(max_length=1000, verbose_name='message')),
            ],
        ),
    ]
