# Generated by Django 4.1.7 on 2023-04-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0009_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosensermon',
            name='sermon_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='fatherpakhomius.sermon', verbose_name='sermon name'),
        ),
    ]
