# Generated by Django 4.1.7 on 2023-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0011_chosensermon_audio_chosensermon_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'User Message', 'verbose_name_plural': 'User Messages'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='date_created'),
        ),
    ]
