# Generated by Django 4.1.7 on 2023-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0012_alter_usermessage_options_sermon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='date_created'),
        ),
    ]
