# Generated by Django 4.1.7 on 2023-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0014_book_author_book_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('article', models.CharField(max_length=5000, verbose_name='article')),
                ('image', models.FileField(upload_to='images', verbose_name='image')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='chosensermon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermoncategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermonsbyotherfather',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
