# Generated by Django 4.1.7 on 2023-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0018_remove_chosensermon_sermon_name_chosensermon_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonsbyotherfather',
            name='author',
        ),
        migrations.AddField(
            model_name='chosensermon',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='audio',
            field=models.FileField(upload_to='audio', verbose_name='sermon audio'),
        ),
    ]
