# Generated by Django 4.1.7 on 2023-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0019_remove_sermonsbyotherfather_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosensermon',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
