# Generated by Django 4.1.7 on 2023-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0022_alter_chosensermon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosensermon',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='date_created'),
        ),
    ]
