# Generated by Django 4.1.7 on 2023-04-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0023_alter_chosensermon_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosensermon',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
    ]
