# Generated by Django 4.1.7 on 2023-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherpakhomius', '0025_alter_book_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='booksbyotherfather',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='chosensermon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermoncategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='sermonsbyotherfather',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
